### ISSUE TITLE
Why do current courses appear in past courses?

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#112]
Hi Ajay!

Past courses should only show courses in the past (not current or future)
Are you able to automatically code this, or can the client choose which posts are past in the backend?

![screen shot 2015-04-15 at 4 53 13 pm](https://cloud.githubusercontent.com/assets/10924897/7169098/60e61bde-e390-11e4-88c0-c629b63fc3d6.png)

**Comment by ajay786singh** [comment]
I have added a course end date field for each courses, where you can enter end date for courses.
