### ISSUE TITLE
Please change us$ to cdn$ in backend of appointment booking

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#127]
Hi Ajay,
Sorry I can't see where to do this myself in the backend. Mind helping me out?

Thanks!
![screen shot 2015-04-21 at 12 09 45 pm](https://cloud.githubusercontent.com/assets/10924897/7256862/9ba12cda-e81f-11e4-87ee-0bed71856038.png)

**Comment by ajay786singh** [comment]
Please check, this is done now.
