### ISSUE TITLE
Consider how to enter all the folk names

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#128]
Hey Lionel!
This question is for you as you uploaded the herb database.
We need to get the folk names added to their respective single herb tinctures.

Can this be done in one shot?
Or does someone need to enter this info individually for all 200 products?

**Comment by lmann** [comment]
@jenphelan I did the initial upload but I *think* Ajay redid it as he had to change custom fields. 

@ajay786singh Can you answer this?

**Comment by ajay786singh** [comment]
Hey @jenphelan For Now we have to do it manually by adding folk name to each product individually. There is no way to update bulk products using csv files or other files formats.

**Comment by jenphelan** [comment]
I understand. Ajay, can you estimate how long this would take to do
manually?

**Comment by ajay786singh** [comment]
Hey @jenphelan It will take about a 5-6 hours approx.

**Comment by ajay786singh** [comment]
Hi @jenphelan PLease send me list of folk names for products.

**Comment by jenphelan** [comment]
The folk names are the first column in the list: https://docs.google.com/a/hypenotic.com/spreadsheets/d/1rnkoHPkRlDNT1yWO7jUDjFKKWNn9NbBb0jjJMb437HA/edit?usp=sharing

**Comment by jenphelan** [comment]
hi @ajay786singh, I'm going to see if the client would rather enter the names themselves (versus us & billing them for it)
I'll get back to you soon about what they decide.

**Comment by jenphelan** [comment]
@ajay786singh please hold off on entering folk names. Client wants to think about whether they would like to do the names themselves instead of pay extra. (especially because they have to enter pictures and prices themselves)

**Comment by ajay786singh** [comment]
This is fixed.
