### ISSUE TITLE
Please check google calendar synching

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#139]
Hi Ajay!

The appointment plugin works great, but I just can't seem to get it to sync with my google calendar. I'm logged in as jen@hypenotic with google chrome, and I'm booking with my jen@hypenotic email.

Do you know why it might not be working?

![screen shot 2015-04-22 at 11 49 24 am](https://cloud.githubusercontent.com/assets/10924897/7278802/b0f2feb2-e8e5-11e4-8b38-6d552ba1714b.png)

**Comment by ajay786singh** [comment]
Hey @jenphelan , Please check it again it is working now. When you click to submit your appointment there should be a pop up box will open after that it will go to another link to save google calendar. 

But before that you should allow popup for this site.

**Comment by jenphelan** [comment]
Thanks I got it!
