### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by SamChun** [hypenotic/viriditas#166]
Please use a real map. We would still like to have the purple colour. Is it a good idea to customize a google map? or place a colour overlay on a google map? We still want this area to be clickable. Let us know what you think.

Increase the height of the map (approx. 500px)

Increase the width of the address area to: approx. 760px

Change "Viriditas" to: 3.125em

Change the rest of the address to: 1.375em

Align "Viriditas" and address to the left margin

Use the image below as a reference

![viriditas-contact](https://cloud.githubusercontent.com/assets/8697960/7372889/4b7053a8-ed97-11e4-866c-fd6d286c7cda.jpg)

**Comment by jenphelan** [comment]
Hey @ajay786singh! Can you make the map show the neighbourhood, instead of the province view? :)
Also, can you have the whole map area clickable and link to the Google Maps page?
