### ISSUE TITLE
How do I show next month schedule in appointment bookng?

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#179]
Hey @rstender :
Here's the problem. It's the end of April, and I want to book an appointment for next week. But I can't jump the next month's schedule!

It says showing multiple months is possible by adding a shortcode, but the link to the shortcode list takes me to a blank page. Can you help oh wizard of wordpress?

**Comment by rstender** [comment]
Hey Jen,
I've added the shortcode to show the next and previous month: 

http://hypelabs.ca/viriditas/appointments/

We may need @ajay786singh to help us figure out why it goes from April straight to June.

Also, styling.
-rs-

**Comment by jenphelan** [comment]
Thanks! @SamChun Can you take a peak and let us know if you'd like to make any changes to the next month buttons?
