### ISSUE TITLE
Can you please make these links buttons?

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#194]
Hi Ajay!

I have links at the end of each services section to take you to their action pages (see screenshots)

Can you give these the same style as the book an appointment button on the contact page?

Thanks!
![screen shot 2015-05-12 at 11 00 45 am](https://cloud.githubusercontent.com/assets/10924897/7590458/a3b19b8a-f896-11e4-9d66-04b3251e08ee.png)

![screen shot 2015-05-12 at 11 01 59 am](https://cloud.githubusercontent.com/assets/10924897/7590436/8b594920-f896-11e4-9dff-e4ca1dd0940f.png)
![screen shot 2015-05-12 at 11 00 55 am](https://cloud.githubusercontent.com/assets/10924897/7590437/8b635e10-f896-11e4-9c01-8f4147b8c200.png)
![screen shot 2015-05-12 at 11 01 55 am](https://cloud.githubusercontent.com/assets/10924897/7590438/8b638b4c-f896-11e4-9461-71bf31c2d295.png)

**Comment by ajay786singh** [comment]
this is fixed please check.

**Comment by jenphelan** [comment]
Nice! thanks!
