### ISSUE TITLE
Can images automatically be cropped to fit the container size?

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#198]
Hi @ajay786singh 
I noticed when I upload images to the site for 'featured images' that the images need to be exactly the correct dimensions otherwise the layout will break.

The client will not be able to crop their images to the right size. Is it possible to have the featured image area automatically crop/ resize the image proportionally to the area it will appear in the layout?

Let me know, thanks!

**Comment by ajay786singh** [comment]
Hey @jenphelan 

Let's discuss this today morning

Thanks :)

**Comment by jenphelan** [comment]
Oops! we forgot to discuss this! Let's chat about it thursday morning.

**Comment by jenphelan** [comment]
Hi @ajay786singh!
I tested uploaded images with the wrong dimensions to the backend, screenshots are attached. Can you make it so 100% of the width fills the width of the container image, and anything longer than the container will not show?

Thanks!

![screen shot 2015-05-14 at 10 43 53 am](https://cloud.githubusercontent.com/assets/10924897/7634029/2f34d1e6-fa26-11e4-9e28-02611a0886cd.png)
![screen shot 2015-05-14 at 10 43 10 am](https://cloud.githubusercontent.com/assets/10924897/7634030/2f36005c-fa26-11e4-929b-df143429e308.png)
