### ISSUE TITLE
Make edits/ additions to herb chart upload

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#220]
Hey @ajay786singh 
The client has a few things to add to the chart. 
You mentioned you were making a new list for a master upload?

Can you make these few changes while you're at it? Her edits are here: https://basecamp.com/1759522/projects/5415572/messages/42228916?enlarge=154777188#attachment_154777188

Let's discuss this together if it's not clear.

**Comment by ajay786singh** [comment]
I have added 3 products as mentioned in doc file. Let's discuss, if there are more changes.
