### ISSUE TITLE
Please make page headers h2

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#248]
Hi @ajay786singh 

Only the header on the hero banner should be h1.
Please make headers on other pages h2.

**Comment by jenphelan** [comment]
![screen shot 2015-06-03 at 3 24 27 pm](https://cloud.githubusercontent.com/assets/10924897/7969745/07a56230-0a07-11e5-9800-e6747bf0f143.png)

**Comment by SamChun** [comment]
Hey Ajay,

- These are on the "about" page and "our family" page.
- Please remove the margin-bottom of these <h2>
