### ISSUE TITLE
Terms of condition

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#259]
This needs text. Discuss with client

![screen shot 2015-06-03 at 3 32 03 pm](https://cloud.githubusercontent.com/assets/10924897/7970202/67a536e4-0a0a-11e5-9854-7a9fe22072b5.png)

**Comment by lionelmann** [comment]
@jenphelan can this be closed

**Comment by jenphelan** [comment]
Not yet, i'll find out tuesday it's status.

**Comment by jenphelan** [comment]
Hi @ajay786singh 

This google doc has the content for terms and conditions page. 
https://docs.google.com/document/d/1_vrEInBAfyZok6AKv6NWwJqGfWhEubCvQM_t182T8_0/edit?usp=sharing

**Comment by ajay786singh** [comment]
This is done in live and dev site both.

**Comment by jenphelan** [comment]
HI @ajay786singh 

This is too hard to read when paragraph text is centred. Can you make the text right align, like the resources? https://hypelabs.ca/viriditas/the-honey-salve/
