### ISSUE TITLE
Please add this herb to the products section

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#288]
Hi @ajay786singh 
Sorry to delegate this to you @ajay786singh, I know I should do this myself. But I don't want to mess up your database by adding content to the wrong place. 

Can you add this single herb tincture to the site? Thanks!!! 

LATIN: Polygonatum multiflorum
FOLK: Solomon's seal
Source: organically grown 1
Plant part: radix
Price: $50 for 500ml 
body system: musculoskeletal
action: musculoskeletal tonic

**Comment by ajay786singh** [comment]
This is added to the products.
