### ISSUE TITLE
Add another text field for side bar on appointments

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#290]
Hi Ajay!

I need to make one more text field on the appointment booking page side bar called 'Need to cancel?'

Can you show me how to add this? Or if it's hardcoded, can you add it, and I'll fill in the text? Thanks!

![screen shot 2015-06-24 at 5 35 01 pm](https://cloud.githubusercontent.com/assets/10924897/8342063/84682be0-1a97-11e5-8085-7a45cd15cd1a.png)

**Comment by ajay786singh** [comment]
This is fixed.
