### ISSUE TITLE
Some of the folk names are italic?

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#327]
Hi @ajay786singh 
When I searched by folk name in the custom compounding herb list, 
The beginning of the list had some latin names, and some of the folk names were in italics.

Can you check this?

Thanks!

![screen shot 2015-07-28 at 10 48 15 am](https://cloud.githubusercontent.com/assets/10924897/8934582/5c47c960-3516-11e5-8ab5-e340cee69dc0.png)

**Comment by ajay786singh** [comment]
This should be fixed. Please check again.
