### ISSUE TITLE
login to order

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#329]
Hi @ajay786singh 

When I tried to add my edited compound to the cart, it asked me to login. 

Don't forget to add the login link to the top menu, and please also make any login call to actions (like this one) link to the login page as well. 
![screen shot 2015-07-28 at 10 54 04 am](https://cloud.githubusercontent.com/assets/10924897/8934807/6dc3dbe2-3517-11e5-9fbb-94591216f511.png)

**Comment by ajay786singh** [comment]
Login and resister section is hidden for now. Only we can access this if we logged in as admin.
