### ISSUE TITLE
Monograph link missing on professional combination product page

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#331]
Hi @ajay786singh 

Noticed the monograph link on professional herbal combination product page is missing!

![screen shot 2015-07-28 at 11 08 20 am](https://cloud.githubusercontent.com/assets/10924897/8935141/2a26a8b8-3519-11e5-9413-981d585c02f8.png)

**Comment by ajay786singh** [comment]
Copy link of monograph you want to attach with professional herbal combination and paste into to edit section on product detail section to professional herbal combination.

**Comment by ajay786singh** [comment]
Let's discuss if you have any question.

Thanks

**Comment by jenphelan** [comment]
Great I understand!
