### ISSUE TITLE
Change to say 'Search Products'

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#333]
Hi @ajay786singh 

The heading on the left, over the product search nav, should say 'Search Products' Instead of 'Make your compound.' 

Thanks!
![screen shot 2015-07-28 at 11 11 23 am](https://cloud.githubusercontent.com/assets/10924897/8935212/966d6ebc-3519-11e5-8937-e59f09afdcb2.png)

**Comment by ajay786singh** [comment]
Make your compound link is removed but there is no need for any Headings, I think. Let's discuss

**Comment by jenphelan** [comment]
agreed.
