### ISSUE TITLE
Immune category-action mix up

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#356]
hi @ajay786singh 

I noticed in a mistake in the body-system/action list.

Under Immune System, there appears an action: 'Integumentary Antiseptic' and a sub action 'Integumentary Astringent.'

Please remove these.
![screen shot 2015-08-06 at 3 00 38 pm](https://cloud.githubusercontent.com/assets/10924897/9120835/99ac5176-3c4c-11e5-91f1-2427fdd906ec.png)

You don't need to add them to the Integumentary body system, they already exist there.

**Comment by ajay786singh** [comment]
This is fixed.
