### ISSUE TITLE
dry herb preparations mixup

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#358]
hi @ajay786singh 

When I search Dry Herb Preparations, there are 6 results, but only 1 (Super Food) is actually a dry herb preparation. Please change the rest to single herb tinctures. 
![screen shot 2015-08-07 at 3 32 26 pm](https://cloud.githubusercontent.com/assets/10924897/9144608/28d00724-3d1c-11e5-9ac1-758df97f9e2b.png)

**Comment by ajay786singh** [comment]
This is fixed. Please check.

**Comment by jenphelan** [comment]
hi @ajay786singh 

Where should I review this: Dev or live site?
I noticed some issues on both
