### ISSUE TITLE
Please send registration emails to Susan

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#361]
Hi @ajay786singh 

Please make sure account registrations go to this email: susan@viriditasherbalproducts.com

![screen shot 2015-08-07 at 4 11 56 pm](https://cloud.githubusercontent.com/assets/10924897/9145017/1ae19d5a-3d1f-11e5-8fec-e8cb146d85cf.png)

**Comment by ajay786singh** [comment]
This is done.
