### ISSUE TITLE
Checkout block

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#366]
hi @ajay786singh 

For some reason I can't complete check-out. I keep getting an error message about the content I've filled din, but I don't understand what is wrong.

The error message tells me all the things that need to be filled in, it doesn't point to what the issue is.

Do you know why this is happening?

![screen shot 2015-08-07 at 4 25 06 pm](https://cloud.githubusercontent.com/assets/10924897/9145275/306d723c-3d21-11e5-95cd-c3e4786d4113.png)

**Comment by ajay786singh** [comment]
Did you check after billing details form there is an option to have different shipping details if yes then fill other details otherwise if shipping details are same as billing so you have to uncheck that shipping details box.
