### ISSUE TITLE
Please change this error text

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#370]
Hi @ajay786singh 

Can you change this error text to read:

'The maximum amount for this herb is 60% when ordering online. To request a greater amount please place your order by phone: 416-767-3428.'

![screen shot 2015-08-07 at 4 45 47 pm](https://cloud.githubusercontent.com/assets/10924897/9145675/7df2cba8-3d24-11e5-87b5-34b25fe1c006.png)

**Comment by ajay786singh** [comment]
this is done.
