### ISSUE TITLE
Custom products appear in main list

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#375]
Hi @ajay786singh 

I found my recipe 'Jen' in the list of products.

We don't want user products to fill the database. And we don't want users to see eachother's personal recipes. 

But we also don't want to create new complex functionality. 

Question:

Should we ask the client to delete user recipes after they have been received, so they don't appear in the collection?

Or, is there an easy way to automatically hide these user recipes?

Let me know.

![screen shot 2015-08-10 at 11 23 33 am](https://cloud.githubusercontent.com/assets/10924897/9175318/092ddb92-3f53-11e5-9223-2514e5de8e75.png)

**Comment by ajay786singh** [comment]
Hi Let's discuss this issue. It has few new functionality.

**Comment by jenphelan** [comment]
answer: only the user can see their products, so we don't need to change anything.
