### ISSUE TITLE
price/ size not showing on product page for topical and dry herbs

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#377]
Hi @ajay786singh 

I need to add unique prices and sizes for Topical Application Products and Dry Herb Preparations. Topical Applications come in 100ml jars, and Dry Herbs come in a variety of gram sizes.

When I add attributes (size and price), it doesn't seem to show on the front end. 

Use Chaga Java as an example. What am I doing wrong? http://viriditasherbalproducts.com/wordpress/wp-admin/post.php?post=1626&action=edit

![screen shot 2015-08-10 at 12 19 55 pm](https://cloud.githubusercontent.com/assets/10924897/9176696/d99137fa-3f5a-11e5-9dc5-d34bfcbf6fd1.png)

**Comment by jenphelan** [comment]
![screen shot 2015-08-10 at 12 18 21 pm](https://cloud.githubusercontent.com/assets/10924897/9176708/e57d2556-3f5a-11e5-8669-17884e1b4d7c.png)

**Comment by ajay786singh** [comment]
This is fixed.
