### ISSUE TITLE
Change these texts 

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#380]
Hi @ajay786singh 

The following auto-text please change:

1. 'Herb sizes should be 100%' 
change to: 'Make sure your herb total equals 100%'

2. 'Herb size can't be more than 60%' 
change to: 'The maximum addition for this herb is 60%'

3. 'Note: This herb is a little more pricey...' 
change to: 'Note: There is an additional fee for this herb: 5$ extra when added to 500ml, 10$ extra when added to 1000ml. 

4. 'Are you sure to close without adding this herb to your recipe?'
change to: 'Are you sure you don't want to add this herb?'

5. Remove '26' pop up

6. 'Congrats!! Your recipe has been added to your cart. Please click to view cart.'
Change to: 'Thank you, this recipe has been added to your cart. View cart/ checkout' (make link from last line)

![screen shot 2015-08-07 at 4 39 45 pm](https://cloud.githubusercontent.com/assets/10924897/9200810/9391a754-4017-11e5-9e77-0147259b0539.png)
 
![screen shot 2015-08-07 at 4 45 47 pm](https://cloud.githubusercontent.com/assets/10924897/9200864/eaef03ca-4017-11e5-8d39-2279edefa76e.png)

![screen shot 2015-08-11 at 10 17 57 am](https://cloud.githubusercontent.com/assets/10924897/9200965/8bbea738-4018-11e5-85e3-616203ee1c85.png)

![screen shot 2015-08-11 at 10 20 45 am](https://cloud.githubusercontent.com/assets/10924897/9201029/e487140e-4018-11e5-9e21-3411ef28deab.png)

![screen shot 2015-08-11 at 10 22 13 am](https://cloud.githubusercontent.com/assets/10924897/9201047/f2c2d5c6-4018-11e5-9031-4784c19fcf4a.png)

![screen shot 2015-08-11 at 10 23 13 am](https://cloud.githubusercontent.com/assets/10924897/9201143/71dc56ac-4019-11e5-8515-767ff9bad1c4.png)

**Comment by ajay786singh** [comment]
This is fixed.
