### ISSUE TITLE
simple product

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#381]
Hi @ajay786singh 

One of the products doesn’t have a size… it comes in a package of 14 pills. Should this be a simple product?

![screen shot 2015-08-11 at 12 09 56 pm](https://cloud.githubusercontent.com/assets/10924897/9203011/9ecafb24-4022-11e5-8781-e1634fb0024f.png)
![screen shot 2015-08-11 at 12 10 42 pm](https://cloud.githubusercontent.com/assets/10924897/9203012/9ecb43ae-4022-11e5-83ca-066fedc3bc01.png)

**Comment by ajay786singh** [comment]
This is fixed. Please check once code updated on live site.
