### ISSUE TITLE
Registration form bugs

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#384]
Hi @ajay786singh 

Issue 1: When I tested the product section registration form, it kept rejecting my first name.

Issue 2: The drop down for provinces doesn't work.

Question: Will entries from this form go to the entries section under forms in wordpress?

![screen shot 2015-08-11 at 5 43 03 pm](https://cloud.githubusercontent.com/assets/10924897/9211538/cc82981e-4050-11e5-9e8e-9cbdbd1520d8.png)
![screen shot 2015-08-11 at 5 43 54 pm](https://cloud.githubusercontent.com/assets/10924897/9211539/cc8e5794-4050-11e5-86fc-4917ea84931b.png)

**Comment by ajay786singh** [comment]
Hey jen, I can register to the site. Please check once again. And all the entries will go to users section in wordpress not in form section because its not a gravity form.

**Comment by ajay786singh** [comment]
if you want to make it using gravity form then https://www.gravityhelp.com/documentation/article/user-registration-add-on/ please have a look on this.
