### ISSUE TITLE
Reg forms should require approval first.

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#387]
Hi @ajay786singh 

Let's discuss the simplest way to remove automatic registration. 

The user flow when registering should be:
1. User fills out registration form
2. User receives a note saying that we will confirm their registration with 48hrs.
3. Viriditas admin reviews their form submission, and manually makes them an official user.
4. Viriditas emails them with a welcome note, confirming they can now login to order products, and provides them with their password and email.  

I think either we consider finding a plugin, or we make this form a simple gravity form, that Viriditas will need to copy the data from and manually create user accounts.

What do you think is the cheapest/ quickest?

**Comment by ajay786singh** [comment]
This is fixed. Check on dev site.
