### ISSUE TITLE
Registration confirmation

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#390]
hi @ajay786singh 

Last step is to make the confirmation page look a different then the register page.

Please change the headline to say: 'Registration almost complete'
Please remove the line: 'Registration complete... go to login page' 
Please remove the sign up form

![screen shot 2015-08-14 at 10 27 04 am](https://cloud.githubusercontent.com/assets/10924897/9276092/e9865e02-426f-11e5-9030-0ae854d00033.png)

**Comment by jenphelan** [comment]
Hi @ajay786singh 

When I tested login I got a 404 page for confirmation.
(This was on the dev site) 
![screen shot 2015-08-17 at 9 18 22 am](https://cloud.githubusercontent.com/assets/10924897/9305749/ccb664da-44c1-11e5-9443-a81ecfdf3916.png)

**Comment by ajay786singh** [comment]
Now try you will see this page. I forgot to add that page from admin but Now it is there.
