### ISSUE TITLE
Checkout doesn't show stripe (backend does)

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#394]
hi @ajay786singh 

On dev site: When I go to checkout, stripe doesn't show as an option. But in backend, stripe is enabled. 

Help :)

![screen shot 2015-08-17 at 9 40 32 am](https://cloud.githubusercontent.com/assets/10924897/9306130/65da4260-44c4-11e5-919e-dbd88ace99ff.png)
![screen shot 2015-08-17 at 9 40 10 am](https://cloud.githubusercontent.com/assets/10924897/9306129/65d9242a-44c4-11e5-8b77-7d104452c5f6.png)

**Comment by ajay786singh** [comment]
this is fixed
