### ISSUE TITLE
HMM... I can't type in the login box

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#395]
hi @ajay786singh 

This is weird! I can't type in the username or password fields on dev site.

![screen shot 2015-08-17 at 9 38 23 am](https://cloud.githubusercontent.com/assets/10924897/9306164/8df5894e-44c4-11e5-9a75-9170a14a8309.png)

**Comment by ajay786singh** [comment]
Hey @jenphelan I tried in most of the browsers and I can type in login form. Please let me know if there is any specific page where you aren't able to type.

**Comment by jenphelan** [comment]
hi @ajay786singh 

For me it seems to be every page this bug exists. 
![screen shot 2015-08-18 at 10 01 17 am](https://cloud.githubusercontent.com/assets/10924897/9331951/31fe8092-4590-11e5-9af7-e29094478a07.png)
![Uploading Screen Shot 2015-08-18 at 10.01.04 AM.png…]()
