### ISSUE TITLE
DIY compound bug

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#414]
Hi @ajay786singh 

2 little issues:

1. I added 10% to my DIY compound, and pressed add to cart. I got a blank pop up, and some code in a pink box. (see screenshot)

2. Next, I added another herb at 90% to bring my total to 100%. Then I pressed add to cart. The pink box with the crazy code didn't go away, and I couldn't go to my cart.

![screen shot 2015-08-26 at 5 29 25 pm](https://cloud.githubusercontent.com/assets/10924897/9506866/7d287418-4c18-11e5-9a02-0ab4e1cbbefc.png)

![screen shot 2015-08-26 at 5 30 17 pm](https://cloud.githubusercontent.com/assets/10924897/9506858/6e43fab2-4c18-11e5-9c1a-68919124e114.png)
![screen shot 2015-08-26 at 5 29 42 pm](https://cloud.githubusercontent.com/assets/10924897/9506859/6e449dd2-4c18-11e5-8721-a1efa66dd38f.png)

**Comment by ajay786singh** [comment]
This is fixed. Please check again.
