### ISSUE TITLE
Page ID?

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#443]
Hi @ajay786singh 

I'm ready to add the app form pages to the sidebar widget. I can't find the page IDs though, where do I look?

![screen shot 2015-09-02 at 5 33 05 pm](https://cloud.githubusercontent.com/assets/10924897/9645315/cde30226-5198-11e5-82a9-0097de27c5a8.png)
![screen shot 2015-09-02 at 5 33 13 pm](https://cloud.githubusercontent.com/assets/10924897/9645316/cdeea176-5198-11e5-9ca0-f66921274848.png)

**Comment by ajay786singh** [comment]
this is done.
