### ISSUE TITLE
Home page: Please link the bottom three links to their respective pages.

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#45]
Link 'Order product' to Shop Page

Link 'Clinic Appointment' to Appointments page

Link 'Courses' to Courses page
![screen shot 2015-03-20 at 10 48 52 am](https://cloud.githubusercontent.com/assets/10924897/6753843/58628638-ceef-11e4-8f99-08304a052a38.png)

**Comment by ajay786singh** [comment]
Please check, This is fixed.
