### ISSUE TITLE
Add link on custom page to FAQ section

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#453]
Hi @ajay786singh 

Please add a link on both of the custom compounding pages to the resources section.
This link should say: "View monographs and worksheets" and should open the FAQ popup. 
The link can have the same style as the 'Back to products' link. Please place it below the back to products link. 

Thankyouu!!

![screen shot 2015-09-04 at 4 55 11 pm](https://cloud.githubusercontent.com/assets/10924897/9694395/4c5ead1a-5326-11e5-9c75-7e39de6d3a51.png)

**Comment by jenphelan** [comment]
Check this, I'm getting a blank rectangle.
![screen shot 2015-09-08 at 10 23 42 am](https://cloud.githubusercontent.com/assets/10924897/9737312/feeb4480-5613-11e5-9b92-ad577ff0a87b.png)

**Comment by ajay786singh** [comment]
This is fixed.
