### ISSUE TITLE
About Page: Need more space under services intro-blurb

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#46]
See mockup vs dev site examples:
![screen shot 2015-03-20 at 10 56 15 am](https://cloud.githubusercontent.com/assets/10924897/6753929/d8f99066-ceef-11e4-92ee-73b765a1dfd3.png)
![screen shot 2015-03-20 at 10 46 41 am](https://cloud.githubusercontent.com/assets/10924897/6753939/e00a7ba4-ceef-11e4-836c-05ff2e201b27.png)

**Comment by ajay786singh** [comment]
Please check, this is fixed.
