### ISSUE TITLE
About Page: Wrong h style for Medicine, Education, Treatment

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#47]
See mockup vs dev site.
![screen shot 2015-03-20 at 10 58 49 am](https://cloud.githubusercontent.com/assets/10924897/6754007/43e9447a-cef0-11e4-9b04-70ef6dcc7a9a.png)
![screen shot 2015-03-20 at 10 58 54 am](https://cloud.githubusercontent.com/assets/10924897/6754008/43f5001c-cef0-11e4-826a-319cdb3eec63.png)

**Comment by ajay786singh** [comment]
Please check, this is fixed.
