### ISSUE TITLE
Team Page: Needs styles implemented

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#48]
See dev site vs Mockup. 
![screen shot 2015-03-20 at 11 08 27 am](https://cloud.githubusercontent.com/assets/10924897/6754205/848a2ea8-cef1-11e4-8e75-ae1d6d061658.png)
![screen shot 2015-03-20 at 11 09 23 am](https://cloud.githubusercontent.com/assets/10924897/6754216/946aa29e-cef1-11e4-9fbf-5eb52d01069c.png)

**Comment by ajay786singh** [comment]
Please check, this is done.
