### ISSUE TITLE
'Approve' user registration email goes to Spam?

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#489]
Hi @ajay786singh 

I approved my application to register as a user on Viriditas. The approve email with my password got sent to my spam inbox. 

Is there any way to make it end up in inbox?

**Comment by ajay786singh** [comment]
@lionelmann Can you help me out for this issue. Actually this is server relating issue. Let's talk about this when you come online.

**Comment by ajay786singh** [comment]
@jenphelan I and Lionel have tested and we are getting mails in inbox directly not in spam. This happens sometimes for few users. It is not a issue.
