### ISSUE TITLE
Login/ register in top nav should be smaller then other nav items. 

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#49]
![screen shot 2015-03-20 at 11 12 01 am](https://cloud.githubusercontent.com/assets/10924897/6754287/f5dafcf4-cef1-11e4-85be-4618d134d4cc.png)
![screen shot 2015-03-20 at 11 12 07 am](https://cloud.githubusercontent.com/assets/10924897/6754288/f5df6320-cef1-11e4-9075-2f86fa887739.png)

**Comment by ajay786singh** [comment]
Please check, This is fixed.
