### ISSUE TITLE
Product inquiry contact form page

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#491]
Hi @ajay786singh 

I click the contact button in the FAQ section, and filled out the contact form for products.

The confirmation message appeared after I submitted, but so did the text telling me to fill out the form.
https://hypelabs.ca/viriditas/product-inquiry-contact-form/

Can you make it so that after the user fills in the form, only the confirmation message appears under the heading?

![screen shot 2015-09-23 at 12 48 42 pm](https://cloud.githubusercontent.com/assets/10924897/10051852/aa4ee0f0-61f1-11e5-80e0-63999b6da638.png)

**Comment by ajay786singh** [comment]
This is fixed. I have added that texts in form description under form settings.
