### ISSUE TITLE
Check that all single herb tinctures have actions & body systems correct

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#496]
hi @ajay786singh 

As we discussed, you will need to review the excel spreadsheet (See 'The MASTER IMPORT' tab), and make sure each herb has all the actions and body systems checked off in the back end.
https://docs.google.com/spreadsheets/d/1rnkoHPkRlDNT1yWO7jUDjFKKWNn9NbBb0jjJMb437HA/edit#gid=1592320893

We'll check in tomorrow on the status of this.

Thanks!

**Comment by ajay786singh** [comment]
This is done.
