### ISSUE TITLE
Help with tax!

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#499]
Hi @ajay786singh 

I have enabled tax on the back end, at 13%. But I can't see it when i go to check-out.
Can you help? Thanks!!

http://viriditasherbalproducts.com/wordpress/wp-admin/admin.php?page=wc-settings&tab=tax&section
![screen shot 2015-09-24 at 5 54 34 pm](https://cloud.githubusercontent.com/assets/10924897/10087962/564ed8ee-62e5-11e5-82e9-06de4ef30336.png)

**Comment by ajay786singh** [comment]
This is done now.
