### ISSUE TITLE
Order of herbs in monograph

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#508]
Hi @ajay786singh 

This might be tricky.

The client needs the herbs in the composition section of the monographs to have a specific order. This is important because the order the ingredients are added affects the reaction the patient will have.

Is it possible in the backend to control the order of the herbs selected, so this order will appear on the front end too? 
Let me know what you think will work best!

![screen shot 2015-09-28 at 11 18 53 am](https://cloud.githubusercontent.com/assets/10924897/10139896/196c3336-65d3-11e5-866d-9c5754cf9a10.png)

**Comment by ajay786singh** [comment]
Hi @jenphelan Order of herbs is not possible but I can make them order in alphabetically. Actually we are selecting them using checkbox so there is no way to make them custom order.

**Comment by jenphelan** [comment]
Ok. Then we will have to discuss removing the check box from monographs, and have the client write in what herbs are in the formula, in the order they appear. 
The client does not want alphabetical.
