### ISSUE TITLE
Issue with uploading/ previewing worksheets

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#526]
Hi @ajay786singh 
On the live site, when you upload a pdf to a new worksheet and click preview, the pdf doesn't show. I wasn't sure if this was because the FAQ section isn't on the live site yet, so I tried n the dev site. 
But on the dev site, the media folder won't let us upload anything!

Please fix so we can upload worksheets to the live site and see them. Thanks!

![screen shot 2015-10-08 at 10 07 20 am](https://cloud.githubusercontent.com/assets/10924897/10368665/6a1de706-6da4-11e5-8e19-3f06ca39d53f.png)

**Comment by ajay786singh** [comment]
@lionelmann can you make uploads folder writable for dev site?

**Comment by lionelmann** [comment]
This is fixed
