### ISSUE TITLE
Mockup Functionality for Product Landing Page

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#53]
We the following info to be pulled into each product landing page:

Associated body systems v
(Drop down list of related links)

Associated actions v
(Drop down list of related links)

Associated indications v
(Drop down list of related links)

View Monograph
(Will be either link to Monograph in new tab, or link to Monograph on external site)

Contact us
(Drop down form, same as in FAQ section)

**Comment by SamChun** [comment]
Add composition list v  (for professional herbal combinations.)
