### ISSUE TITLE
login with hypelabs products

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#548]
Hi @ajay786singh 

I was able to get to hypelabs.ca/viriditas/products without logging in!
This has never happened before. Did something change?

Users should always need to login before seeing products.

**Comment by ajay786singh** [comment]
Hey @jenphelan Nothing change I tried to go products page in hypelabs so it takes me to login page first. Please check may be you were logged in so it directly takes you to products page.

Please check and let me know if you have questions.
