### ISSUE TITLE
FAQ should always appear when user is logged in

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#553]
Hi @ajay786singh 

I notice that when I am on the 'cart' page, thr FAQ section disappears from the top nav. The user may have a quesion about shipping when on this page. Can you make it so that 'FAQ' always shows when the user is logged in?
Thansk!

![screen shot 2015-10-19 at 10 06 19 am](https://cloud.githubusercontent.com/assets/10924897/10579979/3604ff6a-7649-11e5-82d3-300a1796534b.png)

**Comment by ajay786singh** [comment]
This is fixed.
