### ISSUE TITLE
Change 'call us to order' to link to product page (login) when client is ready

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#567]
![screen shot 2015-11-04 at 5 05 19 pm](https://cloud.githubusercontent.com/assets/10924897/10953501/69e42778-8316-11e5-8f3b-2d8d2d12a187.png)

**Comment by jenphelan** [comment]
Places where we need to add links to the product page are below. (Note: they need to login first before they are directed!)

1. Home page, order products link: https://viriditasherbalproducts.com/
![screen shot 2015-11-23 at 12 42 53 pm](https://cloud.githubusercontent.com/assets/10924897/11344518/ce55aa6a-91df-11e5-8f9d-0ecce53219d8.png)

2. About page, materia medica section, link at the bottom should be replaced with a button that says 'Order Products' (like the other buttons on this page)
https://viriditasherbalproducts.com/about/
![screen shot 2015-11-23 at 12 45 20 pm](https://cloud.githubusercontent.com/assets/10924897/11344554/18e3dbc4-91e0-11e5-93b8-f2003c2bebbb.png)

3. Contact page. Remove text 'Call to order! Online ordering coming soon.' Ad another button under 'Book and Appointment' that says 'Order Products.' 

https://viriditasherbalproducts.com/contact/
![screen shot 2015-11-23 at 12 45 55 pm](https://cloud.githubusercontent.com/assets/10924897/11344590/4152915e-91e0-11e5-998b-bc96321d44c5.png)

**Comment by ajay786singh** [comment]
Hey @jenphelan Please change these changes on live site.
