### ISSUE TITLE
error text on product

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#570]
Hi @ajay786singh 

Saw this on a product page, why/ what does it mean? How can we prevent customers from seeing this scary code when they are shopping?

http://viriditasherbalproducts.com/product/achillea-millefolium/

![screen shot 2015-11-04 at 5 40 54 pm](https://cloud.githubusercontent.com/assets/10924897/10954554/251d3804-831c-11e5-8a8e-0723e227fe3a.png)

**Comment by ajay786singh** [comment]
There is no error message I can see. Sometimes it happens because google api doesn't load properly.
