### ISSUE TITLE
bug with registration button

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#585]
Hi @ajay786singh 

The registration button for one of the courses is for some reason breaking the date/ times row of text to much farther below the title than the other courses.

![screen shot 2015-11-05 at 10 39 37 am](https://cloud.githubusercontent.com/assets/10924897/10973008/b178a508-83a9-11e5-8f9f-83ba15088268.png)

http://viriditasherbalproducts.com/courses/

**Comment by ajay786singh** [comment]
it is fixed. Please check
