### ISSUE TITLE
text when there are no custom formulas

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#589]
HI @ajay786singh 

Is it possible to have text on the page under the headline when there are no custom formulas to display?

This text could be: 'You haven't made any custom formulas yet. Click here to get started." (The second sentance could link to the custom formula page)

![screen shot 2015-11-06 at 9 50 03 am](https://cloud.githubusercontent.com/assets/10924897/10999828/31a8173c-846c-11e5-99d3-ccebe0f3ea2d.png)

**Comment by jenphelan** [comment]
Not fixed for me? Let me know what I should see. 
![screen shot 2015-11-09 at 9 48 52 am](https://cloud.githubusercontent.com/assets/10924897/11036545/342055d0-86c7-11e5-9fd0-ec4e92691a53.png)

**Comment by ajay786singh** [comment]
This is fixed. Template was not selected for this page.
