### ISSUE TITLE
format of order confirmation page

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#590]
Hi @ajay786singh 

The order page styles seem a little off. Customer details isn't centered like the other main headings. 

Also, there should be about 70 px between content sections. Please create space between the 'order again' button and the customer details section. 

https://viriditasherbalproducts.com/checkout/order-received/3299/?key=wc_order_563cbfa5d7135

![screen shot 2015-11-06 at 9 57 57 am](https://cloud.githubusercontent.com/assets/10924897/10999973/1558650e-846d-11e5-99bf-3adcf69ff1c9.png)
![screen shot 2015-11-06 at 9 57 15 am](https://cloud.githubusercontent.com/assets/10924897/10999972/1556a278-846d-11e5-8c54-65c6c77afa59.png)

**Comment by jenphelan** [comment]
Hi @ajay786singh 

Can you take another look at this? I don't think this change got merged. 
![screen shot 2015-11-09 at 11 05 30 am](https://cloud.githubusercontent.com/assets/10924897/11038616/ef2b4a7e-86d1-11e5-96a2-0e0595c56103.png)

**Comment by jenphelan** [comment]
Hi @ajay786singh 

This doesn't look fixed to me yet :(

![screen shot 2015-11-10 at 5 28 47 pm](https://cloud.githubusercontent.com/assets/10924897/11077959/d1014698-87d0-11e5-94ae-1367a9393bde.png)

**Comment by ajay786singh** [comment]
Please check again. this is fixed.

**Comment by ajay786singh** [comment]
Please check here, I can see it is fixed: https://drive.google.com/a/hypenotic.com/file/d/0B6CXgxRdW96weXZBZ0lEXzVpOHM/view?usp=drivesdk
