### ISSUE TITLE
Add user deny email notification

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#610]
Hi @ajay786singh 

If viriditas decides to deny a user submission, is there an automatic email that tells the user they have been denied? If so, where can I edit it?

**Comment by jenphelan** [comment]
yes there is a denial message, ajay is looking into where it can be edited.

**Comment by jenphelan** [comment]
Hi @ajay786singh 

This is the text you can use in the user denied email:

We welcome you to Viriditas and are glad that you have tried to register with us.
At this time, your application has been denied because you may not have supplied one of the following requirements.
1.    What is your health practitioner title?
2.    What educational institute did you attend?
3.    What is your license number?

To re-submit your application go to: https://viriditasherbalproducts.com/register/
If you have any questions, you may contact us at: info@viriditasherbalproducts.com

**Comment by jenphelan** [comment]
Hi @ajay786singh 
I registered, and denied my user application. but i didn’t get an email. Can you check that the denied user notification goes to the email of the person who tried to register?

**Comment by ajay786singh** [comment]
It is working actually may be it takes time to get email. I have checked on dev using my id and its working. Please check again

**Comment by jenphelan** [comment]
forward to jen
