### ISSUE TITLE
Button to generate new password for Chris doesn't work.

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#629]
Hi @ajay786singh 

We tried to generate a new password for Chris Lamont (administrator), but the button in the backend wouldn't work. It works for other users (both subscriber and administrator),

help!

**Comment by ajay786singh** [comment]
Hi @jenphelan, This problem occurs because of appointment plugin google calendar is not connected properly. Please check https://support.google.com/a/answer/60765?hl=en
