### ISSUE TITLE
error message- important!!

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#672]
Hi @ajay786singh 

I'm getting an error message on product pages.
I hard refreshed and clear my cache, but it doesn't go away!
No content will show for product pages on the front end

http://viriditasherbalproducts.com/product/achillea-millefolium/

![screen shot 2015-12-02 at 4 22 20 pm](https://cloud.githubusercontent.com/assets/10924897/11544687/2bafec88-9911-11e5-8299-493394fc0976.png)

**Comment by ajay786singh** [comment]
I didnt see any error message. But I think it is fixed on this update.
