### ISSUE TITLE
Bug with Monographs, backend

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#675]
Hi @ajay786singh 

The client says that when they have been adding content to Monographs and press update, their content is erased. In particular, with this monograph: https://viriditasherbalproducts.com/wordpress/wp-admin/post.php?post=3872&action=edit

This has happened to me before on the Hypenotic site, but I found a link that said:'A more recent version of this post exists. Restore?' And that fixed it for me. 

Unfortunately, when I go to inspect the backend of the  Monograph post, I don't see controls to view revision history, or restore. It looks like it's missing.

Can you check why this is missing?
And if you have any idea why this glitch happening, let's discuss. Could it be updates needed for WP?

**Comment by ajay786singh** [comment]
Please  check it is working fine now.
