### ISSUE TITLE
Can't find 'Education' page in backend?

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#68]
Hi Ajay,

I'm adding content to the back end for the about page, and I have edited Serices, and philosophy, but I can't find the three other sections to edit. Can you help me locate them? Thanks!
![screen shot 2015-03-23 at 2 04 19 pm](https://cloud.githubusercontent.com/assets/10924897/6786923/8b57096a-d165-11e4-9d5f-ed706c21500a.png)
![screen shot 2015-03-23 at 2 01 52 pm](https://cloud.githubusercontent.com/assets/10924897/6786924/8b5b2536-d165-11e4-9b6b-0200841194ec.png)

**Comment by ajay786singh** [comment]
Go to Services section in admin. It is a separate post type.

**Comment by jenphelan** [comment]
That was easy! Thanks Ajay.
