### ISSUE TITLE
Worksheet file upload/ replace doesn't work

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#686]
Hi @ajay786singh 

For some reason, we can't add or replace exsiting worksheet files. The button select just doesn't do anything anymore. Can you check this?

https://viriditasherbalproducts.com/wordpress/wp-admin/post.php?post=3683&action=edit

![screen shot 2015-12-07 at 1 31 57 pm](https://cloud.githubusercontent.com/assets/10924897/11635848/155093dc-9ce7-11e5-9e5e-b8263b11b98d.png)

**Comment by ajay786singh** [comment]
Hey Lionel,
Please change custom page url from wp-config.php file to fix this issue.
