### ISSUE TITLE
DIY compound search

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#687]
Hi @ajay786singh 

I'm having some trouble with the DIY search, that I didn't have before. 
https://viriditasherbalproducts.com/make-your-compound/

If you choose a letter to search by, this letter limits the keyword search. This is confusing, because a peron who enters a keyword wants to search the whole list, not just one letter. Please make it so the keyword search refreshes and cancels out any other search filters.

When an alphabet letter is selected, there is no way to then uncheck alphabet search, and go back to the full list view. Can you have an uncheck letter of alphabet button, like how we have on the home page?. 

Thanks!

![screen shot 2015-12-07 at 2 11 18 pm](https://cloud.githubusercontent.com/assets/10924897/11637057/68ec1e48-9ced-11e5-83e2-b20b0bca3b12.png)
![screen shot 2015-12-07 at 2 15 17 pm](https://cloud.githubusercontent.com/assets/10924897/11637060/68f77658-9ced-11e5-8bd7-01ae499326f6.png)
![screen shot 2015-12-07 at 2 14 51 pm](https://cloud.githubusercontent.com/assets/10924897/11637059/68f4d10a-9ced-11e5-9a22-5bda9cb37b7a.png)

**Comment by ajay786singh** [comment]
Hey Jen, 

Let's discuss this.

**Comment by jenphelan** [comment]
As per our discussion:

Right now, if a keyword is in the search box, and i select a body system, this keyword will limit what shows in the search results for that body system. Body system should override any other filters.
Just like the product page

Add dash to top of alphabet to clear letter search.

**Comment by jenphelan** [comment]
Hi @ajay786singh 

I noticed there's an 'x' in the custom compound keyword box.
But it doesn't do anything. Do we need it?

![screen shot 2015-12-10 at 10 03 18 am](https://cloud.githubusercontent.com/assets/10924897/11718733/6ea4a42e-9f25-11e5-8b23-3ccdfb73f5ba.png)
