### ISSUE TITLE
Monograph link redirects to my account page

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#688]
Hi @ajay786singh 

New development: When i clikc on any professional herbal combination mnograph link from a product page, i am re-directed to the my account page. What's happening?
https://viriditasherbalproducts.com/product/altera-lymph-2/

**Comment by ajay786singh** [comment]
This is fixed. The problem occurs becuase we have changed all site to https and these monograph links are hardcoded in admin. So need to change urls that I did and it is fixed now,
