### ISSUE TITLE
How to edit the home page?

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#69]
Hi Ajay!

When we're ready to swap out pictures and add real content to the home page, is there a place to do this on backend, or do we need to get you to do it for us?

**Comment by jenphelan** [comment]
Hi Ajay! I can open all the parts and edit, except for the section in the middle: 'What we do' Can you add this to the backend? thanks!
![screen shot 2015-03-25 at 10 59 48 am](https://cloud.githubusercontent.com/assets/10924897/6827536/4501e47e-d2de-11e4-88b2-de911b90d00c.png)

**Comment by ajay786singh** [comment]
Hey please check this link: http://hypelabs.ca/viriditas/wordpress/wp-admin/post.php?post=1105&action=edit&message=1

**Comment by jenphelan** [comment]
thanks Ajay! didn't see the second page.
