### ISSUE TITLE
lag with appointment booking

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#692]
Hi @ajay786singh 

The client told us that her clients couldn't book appointments in January, even though the settigns are set to 3 months in advance booking. I tested this, and was able to go to the next month and book, but it took 22 seconds until the the january calender opened. 

Can you check why there's so much lag in the appointments section?

**Comment by lionelmann** [comment]
This should be running faster now with the plugin upgrade. Closing this. Reopen if this is still an issue.
