### ISSUE TITLE
FAQ doesn't open on non-product pages

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#708]
Hi @ajay786singh 

The link for FAQ is always there when the user is logged in, but it doesn't open properly on non product pages. See screenshot:

![screen shot 2015-12-15 at 10 02 30 am](https://cloud.githubusercontent.com/assets/10924897/11814122/2aa2e35c-a313-11e5-8a52-2e6f138e75c7.png)

**Comment by ajay786singh** [comment]
fixed
