### ISSUE TITLE
Resources blog can be set up

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#71]
Hi Ajay,

I've created categories for the blog, and added a few posts from the essay category. 
Can you set up the blog archive, populate it with the posts I've made, and have it show on the main nav?
Thanks!

**Comment by jenphelan** [comment]
Hi Ajay! I set up the resources section myself. But I need your help to build the archive list on the left.
You can use the style from the courses page (see screen shot)
There will be a lot of posts per category, so please enable 'hide and reveal' functionality for each category. 

![screen shot 2015-03-25 at 12 03 20 pm](https://cloud.githubusercontent.com/assets/10924897/6829040/68d01d18-d2e7-11e4-93d9-2b5277faf2e9.png)

**Comment by jenphelan** [comment]
Also, we'll need you to add next article, previous article functionality to the bottom of the post.

**Comment by jenphelan** [comment]
Hi Ajay!

You've put the forms section on the left column, but i need the blog archive to appear here. Instead of forms, it should show the categories and tags.

![screen shot 2015-03-26 at 9 50 48 am](https://cloud.githubusercontent.com/assets/10924897/6847534/cf0babae-d39d-11e4-885a-a420abe5401c.png)
![screen shot 2015-03-26 at 9 50 03 am](https://cloud.githubusercontent.com/assets/10924897/6847535/cf0e9f8a-d39d-11e4-8932-094b16037ff1.png)

**Comment by ajay786singh** [comment]
Please check, this is fixed.
