### ISSUE TITLE
question about separating FAQs

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#713]
Hi @ajay786singh 

The client wants to know if we can seperate FAQ into three seperate links in the top nav bar:
FAQ (would always be in the top nav, visible to public)
Worksheets (only visible after logged in)
Monographs (only visible after logged in)

Sorry, I know this is not what we all originally agreed on. 

Can you let me know how much time it would take, so I can tell them cost?

**Comment by ajay786singh** [comment]
Hey @jenphelan ,

It will take about 2 hours to fix it.

**Comment by jenphelan** [comment]
Client decided to leave it as is. Nevermind!
