### ISSUE TITLE
enhancement to quote

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#715]
Hi @ajay786singh 

Can you quote how long this would take? 

The clients wants to have check boxes beside the thumbnail products for add to cart, so the user doesn't always have to open the product page to add to cart. The user would decide ml during cart/checkout. 

There are most interested in this feature for list view.

Please let me know if you can do it, and how much time it would take.

Thankyou!

**Comment by ajay786singh** [comment]
Hey @jenphelan Let's discuss this today morning.
