### ISSUE TITLE
content from team page disappeared on front end!

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#79]
I needed to change the name of the page 'team' to 'our family' but when I did, all the content that page pulls in disappeared from the front end. 

I changed the name back to what it was (team), but that didn't bring the content back.

I need you to make it so we can change the name of pages without breaking the pieces!

Thanks!

![screen shot 2015-03-26 at 12 34 00 pm](https://cloud.githubusercontent.com/assets/10924897/6851300/9f7903ca-d3b4-11e4-90ac-925c1e704a82.png)

**Comment by ajay786singh** [comment]
Please check now. It is working.

**Comment by jenphelan** [comment]
thanks ajay! 

If i change the name to 'our family' instead of 'team' should everything still work okay?
