### ISSUE TITLE
Swap out b&w logo on team page for colour big version

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#82]
Hi Ajay!

The client would like you to replace the b&w logo on the team page in two places:
Above production team
Above Clinic Team

With the big colour version like you've used in the footer.

Thanks!

![screen shot 2015-03-30 at 3 38 18 pm](https://cloud.githubusercontent.com/assets/10924897/6905032/1bddb014-d6f3-11e4-8a86-76f67dfe0499.png)
![screen shot 2015-03-30 at 3 38 13 pm](https://cloud.githubusercontent.com/assets/10924897/6905033/1be02254-d6f3-11e4-859e-21c4a8573a64.png)

**Comment by jenphelan** [comment]
Thanks Ajay!

One more thing, are you able to make the colour logos bigger? Almost same size as in the footer.

Thanks.

**Comment by ajay786singh** [comment]
Please check this is done
