### ISSUE TITLE
Please darken body copy style and light grey subhead style

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#86]
Hi Ajay!

A favour:

Can you please make these two styles (light grey subhead and body text) 15% darker?

This is top priority, if possible please modify by tomorrow. Thanks!

**Comment by jenphelan** [comment]
![screen shot 2015-04-01 at 2 27 57 pm](https://cloud.githubusercontent.com/assets/10924897/6948405/a830496c-d87b-11e4-8419-3afe215d8152.png)

**Comment by ajay786singh** [comment]
Please check, this is fixed.
