### ISSUE TITLE
Please make 'choose practitioner' the first step in appointment booking

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#87]
Hi Ajay!

Please make choose a practitioner step 1, and select a service step 2.

Thanks!

![screen shot 2015-04-01 at 2 31 29 pm](https://cloud.githubusercontent.com/assets/10924897/6948467/f9af63ea-d87b-11e4-9976-1e41df8dafa5.png)

**Comment by ajay786singh** [comment]
Please check this is fixed.

**Comment by jenphelan** [comment]
Hey Ajay,

Now only one practitioner shows in the first drop down, and the services show ALL the services, instead of just the ones linked to John. 
I've already set up the functionality for this in the backend. Can you make it show on front end?

Thanks!
