### ISSUE TITLE
Help me add additional content to side bar on appointments

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#88]
Hi Ajay, can you create another text area under the side bar of appointments?

I need you to add the following:

(Heading) FIRST TIME PATIENTS
(text) Please go to “Our Family / Clinic Team” (link to our family page) to learn about who we are so that you can choose the person & service that suits your needs.

![screen shot 2015-04-01 at 3 34 50 pm](https://cloud.githubusercontent.com/assets/10924897/6949829/a83df82e-d884-11e4-851c-2dfef2850a01.png)

![screen shot 2015-04-01 at 3 32 52 pm](https://cloud.githubusercontent.com/assets/10924897/6949815/9fd2ae96-d884-11e4-8bec-ca6b4574bb56.png)

**Comment by ajay786singh** [comment]
Please check, this is done.
