### ISSUE TITLE
Newsletter sign up text gets cut off

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/viriditas#97]
Hi Ajay,

Can you make it so text doesn't get cut off under the newsletter signup? Perhaps make it wrap, or specify safe word count?

![screen shot 2015-04-09 at 3 40 52 pm](https://cloud.githubusercontent.com/assets/10924897/7075308/efdc1076-dece-11e4-8221-a686e9005528.png)

**Comment by rstender** [comment]
I took a screenshot, too! 

![viriditas-email-form](https://cloud.githubusercontent.com/assets/1899319/7076362/d74d0cba-ded6-11e4-83c2-22156aedca4a.png)
